# Permalinks
permalink: '/announcements/:title'

# Setup
title: Fluent.Ribbon
tagline: ''
description: ''
url: https://fluentribbon.github.io

paginate: 5
paginate_path: '/announcements/:num'

# Dependencies
markdown: kramdown

kramdown:
  input: GFM

highligther: rouge

plugins:
   - jekyll-coffeescript
   - jekyll-paginate