# Dependencies
markdown: kramdown

kramdown:
  input: GFM

highligther: pygments

# Permalinks
permalink: '/announcements/:title'

# Setup
title: Fluent.Ribbon
tagline: ''
description: ''
url: http://fluentribbon.github.io